#!/usr/bin/env python3
"""Synthesise the CRT power on/off sounds.

    python3 Tools/MakeSounds.py [repo-root]

Written the way `Tools/MakeIcons.swift` draws the icon: the assets are generated from
code and committed, so changing them means changing this file rather than hunting for
whoever has the originals.

Generated rather than recorded or sampled, and that is the point. Everything in this
bundle is deliberately unencumbered — the music is AI-generated by ws4kp's author
specifically so no rights holder exists, and the App Store record declares
USES_THIRD_PARTY_CONTENT. A CRT thunk pulled from a sample library or lifted off a
recording would be the first thing shipped that is somebody else's property. Arithmetic
has no licence.

Pure standard library on purpose: `wave`, `math`, `struct` and `random` are always
present, so this runs on a clean machine with no pip install. (`MakeIcons.swift` is in
Swift for the same reason, since CoreGraphics ships with Xcode while Pillow does not.)

## What is being imitated

A CRT switching off is three sounds at once:

  * The flyback transformer, which whines at the horizontal scan frequency — 15,734 Hz
    on NTSC, the real number, not a round one. When the high voltage collapses the pitch
    falls as it dies.
  * The degauss coil and the mains relay: a low thump you feel more than hear.
  * The static crack of the anode discharging into the tube face.

Switching on runs the same three in reverse, and takes longer: the heater has to warm
before the raster appears.

The whine is kept quiet. It sits near the top of adult hearing, plenty of people cannot
hear it at all, and anyone who can should notice it rather than be bothered by it.
"""

from __future__ import annotations

import math
import random
import struct
import sys
import wave
from pathlib import Path

SAMPLE_RATE = 44_100
# NTSC horizontal scan frequency. This is what a CRT actually whines at.
FLYBACK_HZ = 15_734.264


def envelope(t: float, duration: float, attack: float, decay: float) -> float:
    """Attack-then-exponential-decay, both in seconds."""
    if t < 0 or t > duration:
        return 0.0
    if t < attack:
        return t / attack if attack > 0 else 1.0
    fade = math.exp(-(t - attack) / max(decay, 1e-6))
    # Taper the last 15% to zero so the file cannot click at its own end.
    tail = duration * 0.15
    if t > duration - tail:
        fade *= (duration - t) / tail
    return fade


def sweep(t: float, start_hz: float, end_hz: float, duration: float) -> float:
    """Phase of a tone gliding exponentially from `start_hz` to `end_hz`.

    Exponential rather than linear because pitch is perceived logarithmically; a linear
    sweep spends most of its time sounding like it has already arrived.
    """
    progress = min(max(t / duration, 0.0), 1.0)
    hz = start_hz * ((end_hz / start_hz) ** progress)
    return hz


def render(duration: float, layers) -> list[float]:
    """Sum `layers` — each a function of (t, index) returning a sample — into a buffer."""
    count = int(SAMPLE_RATE * duration)
    out = [0.0] * count
    for layer in layers:
        phase = 0.0
        for i in range(count):
            t = i / SAMPLE_RATE
            value, phase = layer(t, phase)
            out[i] += value
    return out


def whine(start_hz: float, end_hz: float, duration: float, level: float, attack: float, decay: float):
    """The flyback transformer. Phase is accumulated so a sweep does not tear."""
    def layer(t: float, phase: float):
        hz = sweep(t, start_hz, end_hz, duration)
        phase += 2 * math.pi * hz / SAMPLE_RATE
        return math.sin(phase) * level * envelope(t, duration, attack, decay), phase
    return layer


def thump(hz: float, duration: float, level: float, decay: float):
    """The relay and degauss coil: a damped low sine."""
    def layer(t: float, phase: float):
        phase += 2 * math.pi * hz / SAMPLE_RATE
        return math.sin(phase) * level * envelope(t, duration, 0.004, decay), phase
    return layer


def crackle(duration: float, level: float, decay: float, smoothing: float):
    """Anode discharge: white noise through a one-pole lowpass, so it hisses not fizzes."""
    state = 0.0

    def layer(t: float, phase: float):
        nonlocal state
        state += (random.uniform(-1.0, 1.0) - state) * smoothing
        return state * level * envelope(t, duration, 0.001, decay), phase
    return layer


def write_wav(path: Path, samples: list[float]) -> None:
    peak = max((abs(s) for s in samples), default=1.0) or 1.0
    # Normalise to -3 dBFS. Loud enough to hear over the music bed, quiet enough that it
    # is a detail rather than an event.
    gain = 0.708 / peak
    frames = b"".join(
        struct.pack("<h", int(max(-1.0, min(1.0, s * gain)) * 32767)) for s in samples
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as f:
        f.setnchannels(1)
        f.setsampwidth(2)
        f.setframerate(SAMPLE_RATE)
        f.writeframes(frames)
    print(f"  {path.name:22} {len(samples) / SAMPLE_RATE:.2f}s  {len(frames) + 44:,} bytes")


def power_off() -> list[float]:
    """High voltage collapsing: the whine falls away, the coil thumps, the tube cracks.

    Kept to 0.40s so it finishes just after the 0.28s raster collapse it accompanies.
    """
    duration = 0.40
    return render(duration, [
        whine(FLYBACK_HZ, 240.0, duration, level=0.22, attack=0.001, decay=0.075),
        thump(62.0, duration, level=0.85, decay=0.085),
        crackle(duration, level=0.30, decay=0.045, smoothing=0.55),
    ])


def power_on() -> list[float]:
    """The reverse, and slower: the heater warms before the raster arrives."""
    duration = 0.55
    return render(duration, [
        # Rises to pitch and then holds, so it settles rather than overshooting.
        whine(900.0, FLYBACK_HZ, duration * 0.75, level=0.18, attack=0.16, decay=0.55),
        thump(74.0, duration, level=0.75, decay=0.060),
        crackle(duration, level=0.22, decay=0.10, smoothing=0.35),
    ])


def main() -> None:
    random.seed(4000)  # Deterministic: regenerating must not churn the committed files.
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent
    out = root / "Packages/WeatherStarCore/Sources/WeatherStarResources/Assets/Sounds"
    print(f"writing to {out}")
    write_wav(out / "crt-power-off.wav", power_off())
    write_wav(out / "crt-power-on.wav", power_on())


if __name__ == "__main__":
    main()
